### PR TITLE
Add CLI options and make scripts more friendly

### PR DESCRIPTION
**Pull request by McSim85**
Hello Mr. Menhart,
Thank you very much for making the script "make_chroot_jail".
I am really excited about it because it is very useful.
I've made some improvement into the script and I will be appreciated to approve my Pull request.
We can make your script better together by the open-source community. :)
Most of the changes are:
 * tested on Debian 9
 * added more friendly help
 * script became more talkative
 * Added lots of CLI options (see -h option)
 * if you use a single partition, you can use hard links instead of copy (use -l, --link options)
 * removed APPS: cat more less nano (now, you can add it by CLI option -a )

Thank you again and have a nice day.

### CODE REVIEW

**Comment by pmenhart** [comment]
Hello Maksim,
Your additions are extensive and impressive! Instead of accepting as a PR, I suggest to make your repository as the main source. 
I'll add a note to my README - any reader can follow the link to get the new version from your repo. Please let me know whether you are OK with such arrangement.

All the best
Peter

**Comment by McSim85** [comment]
Hi Peter,
I agree with your arrangement.
Thank you for your cooperation :)

**Comment by McSim85** [comment]
So Peter,
Just to be clear :)
Would you like to just place a comment into the README?
Or would you like to transfer the repository?

Thank you. Stay safe ;-)

**Comment by pmenhart** [comment]
Hi Maksim,

I added a note to the README.
There is not much value in transferring the repo, and I'd like to keep the old/simple version for my reference. I hope you are OK with this arrangement.

Take care
Peter

**Comment by McSim85** [comment]
Peter,
Sure, it is a perfect arrangement.
Thank you for your help and for reference.
Have a nice day!

**Pull request closed without merging**
